# Generated by Django 5.1.4 on 2025-05-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='therapist',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='available_days',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='experience_years',
        ),
    ]
