# Generated by Django 5.1.4 on 2025-05-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_system', '0002_rename_phone_parent_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='experience_years',
            field=models.IntegerField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
