# Generated by Django 5.1.4 on 2025-05-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_system', '0003_therapist_experience_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='experience_years',
            field=models.IntegerField(),
        ),
    ]
