# Generated by Django 5.1.4 on 2025-05-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_system', '0004_alter_therapist_experience_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
