# Generated by Django 5.1.4 on 2025-05-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_system', '0005_parent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='availability',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='morning', max_length=20),
        ),
    ]
