# Generated by Django 5.1.4 on 2025-05-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_system', '0006_therapist_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='availability',
        ),
        migrations.AddField(
            model_name='therapist',
            name='available_afternoon',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='available_evening',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='available_morning',
            field=models.BooleanField(default=True),
        ),
    ]
