# Generated by Django 5.1.4 on 2025-05-23 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_system', '0007_remove_therapist_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapysession',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_sessions', to='scheduling_system.therapist'),
        ),
    ]
