# Generated by Django 5.1.4 on 2025-05-29 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_system', '0008_alter_therapysession_therapist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling_system.therapist')),
            ],
            options={
                'unique_together': {('therapist', 'date')},
            },
        ),
    ]
